
# Dependencies
gems:
  - jekyll-paginate
#  - jekyll-minifier

# Permalinks
permalink:                pretty
relative_permalinks:      false

# About
title:                    watermint.org
tagline:                  "Takayuki Okazaki's note"
description:              'Travel, camera, photo, and technical things. I work at Dropbox. Thoughts are my own.'

# Url
url:                      'http://watermint.org'
baseurl:                  ''
paginate:                 5

# Markdown
markdown:                 kramdown

kramdown:
  input:                  GFM
  hard_wrap:              false
  syntax_highlighter:     rouge

# Contact
author:
  name:                   Takayuki Okazaki
  url:                    https://twitter.com/watermint

# Minify
# jekyll-minifier:
#   exclude:                'atom.xml'
